blank_issues_enabled: false
contact_links:
  - name: â“ Help and support, feature requests
    url: https://discord.gg/GrMGspZ
    about: Please ask questions on our Discord server. This issue tracker is only for formatted reports.
